### ISSUE TITLE
Can't load custom unit (OSC Input, OSC Output)

### ISSUE THREAD

**Issue by silicatproject** [keijiro/BoltOscJack#4]
Hello,
I'm probably missing something, OscJackVS is well installed but I can't see the differents custom units in the flow graph search window.
Any ideas?
Thank you very much
Mathieu

Unity 2021.1.9f1
Bolt 1.4.15

**Comment by keijiro** [comment]
OscJackVS has migrated from Bolt to Unity built-in Visual Scripting. Please consider migrating your project from Bolt to Unity VS too.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
