### ISSUE TITLE
Quaternion to OSC

### ISSUE THREAD

**Issue by ElbyB** [keijiro/BoltOscJack#5]
Hi,

Would it be possible to make an OSC node that can handle Quaternions?

Thanks!

**Comment by keijiro** [comment]
You should convert Quaternion to Vector4 before sending it.

(That's a bit cumbersome, but I think it's a valid way because OSC doesn't support quaternion natively.)

**Comment by ElbyB** [comment]
Hi,

Thanks for the answer! I tried this without success. I was able to get the 4 float of Quaternion separately, but how can I put them back together as a Vector4?
