### ISSUE TITLE
Compile error on install

### ISSUE THREAD

**Issue by ShijiMi-Soup** [keijiro/BoltOscJack#6]
Hey, thanks for the great project!

I face this error when I install OSCJackVS

> Library/PackageCache/jp.keijiro.osc-jack.visualscripting@2.0.0/Runtime/OscStringInput.cs(11,34): error CS0535: 'OscStringInput' does not implement interface member 'IGraphEventListener.StopListening(GraphStack, bool)'

I recorded the steps that I followed. Are there any other things to do to install this package?

https://github.com/keijiro/OscJackVS/assets/52814191/00472186-20ed-483a-97cc-bfbc80c27553

**Comment by keijiro** [comment]
There were compatibility breaking issues in Visual Scripting 1.9.0. You should update it to 1.9.1 to avoid the issue.

https://docs.unity3d.com/Packages/com.unity.visualscripting@1.9/changelog/CHANGELOG.html

> [1.9.1] - 2023-08-15
> ### Fixed
> - Reverted a breaking change where LudiqScriptableObject._data was marked as private
> - Reverted a breaking change related to IGraphEventListener
